name: Netlify Builds

on:
  schedule:
    - cron: "00 22 */3 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
